openapi: 3.1.0
info:
  title: NoteAPI
  version: 0.1.0
servers:
  - url: https://noteapi.gould.pro
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /health:
    get:
      operationId: health
      summary: Health check
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
  /search:
    get:
      operationId: searchNotes
      summary: Full-text search
      parameters:
        - in: query
          name: q
          required: true
          schema:
            type: string
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 50
      responses:
        "200":
          description: Results
          content:
            application/json:
              schema:
                type: object
                properties:
                  hits:
                    type: array
        "201":
          description: Created